nombres = {
    "Abigail",
    "Addams",
    "Adivar",
    "Agnesi",
    "Alcott",
    "Ariadne",
    "Aurelia",
    "Balch",
    "Barton",
    "Buck",
    "Cleopatra",
    "Cunitz",
    "Danilova",
    "De Lalande",
    "Dickinson",
    "Dorothy",
    "Goeppert-Mayer",
    "Golubkina",
    "Gregory",
    "Grimke",
    "Guilbert",
    "Irina",
    "Isabella",
    "Maria Celeste",
    "Mariko",
    "Mead",
    "Meitner",
    "Merit Ptah",
    "Mona Lisa",
    "Riley",
    "Ruth",
    "Sophia",
    "Stefania",
    "Wanda",
    "Wheatley",
    "Yablochkina"
}
